#!/bin/sh
# Write gles_stubs.h: one stub per possible dispatch slot, for the slots the shim cannot name.
#
#   genstubs.sh OUT.h
#
# Every slot of the framework's table needs a real function pointer. OpenGLES's trampolines load blindly from the
# table -- there is no null check anywhere in them -- so a slot left at zero is a branch to address 0 the first time
# an app touches it. A slot whose dispatch field the name table (include/hw/arm/guest-services/gles-names.h) does not
# know gets stub N, which reports itself by slot (mbxshim's gles_unknown_slot names the field) and returns 0. Named
# slots never come here: they get a forwarder or a by-name stub from the table.
#
# Each stub takes only the GC. Extra arguments the caller passed in r1-r3 or on the stack are simply ignored, which is
# safe under AAPCS: the caller cleans up its own stack arguments. (slotmap.txt, the 3.1.3 slot -> name map the tests
# read, was recovered once from the 3.1.3 SDK's trampolines and is kept as data.)
set -eu
# Room for every layout seen (822, 826, 841; 6.x 914, 7.x 1035 slots) and then some; GLESCreateGC and glishim refuse more.
awk -v n=1152 'BEGIN {
    print "/* Generated by genstubs.sh -- do not edit. */\n#ifndef GLES_STUBS_H\n#define GLES_STUBS_H\n"
    print "static int gles_unknown_slot(unsigned slot);\n"
    for (i = 0; i < n; i++) printf "static int u%d(void *gc) { (void)gc; return gles_unknown_slot(%d); }\n", i, i
    printf "\n#define GLES_MAX_SLOTS %d\nstatic void *const gles_unknown_table[GLES_MAX_SLOTS] = {\n", n
    for (i = 0; i < n; i += 8) {
        line = ""
        for (j = i; j < i + 8 && j < n; j++) line = line (j > i ? ", " : "") "(void *)u" j
        print "    " line ","
    }
    print "};\n\n#endif"
}' > "$1"
