#!/usr/bin/env python3
"""Generate gles_stubs.h: one thunk per dispatch slot, plus the default table.

Every slot needs a real function pointer. OpenGLES.framework's trampolines load
blindly from the table -- there is no null check anywhere in them -- so a slot we
leave at zero is not "unimplemented", it is a branch to address 0 the first time
an app touches it. Filling all 822 entries with a thunk that reports itself and
returns 0 turns "we do not implement that yet" from a crash into a log line.

Each thunk takes only the GC. Extra arguments the caller passed in r1-r3 or on
the stack are simply ignored, which is safe under AAPCS: the caller cleans up
its own stack arguments.
"""
import sys

# X+0x10 .. X+0xCE8 is the dispatch table, so 0xCD8/4 entries.
N_SLOTS = (0xCE8 - 0x10) // 4

out = ["/* Generated by genstubs.py -- do not edit. */",
       "#ifndef GLES_STUBS_H",
       "#define GLES_STUBS_H",
       "",
       "extern int gles_unimpl(unsigned slot);",
       ""]

for i in range(N_SLOTS):
    out.append("static int u%d(void *gc) { (void)gc; return gles_unimpl(%d); }" % (i, i))

out.append("")
out.append("#define GLES_N_SLOTS %d" % N_SLOTS)
out.append("static void *const gles_default_table[GLES_N_SLOTS] = {")
for i in range(0, N_SLOTS, 8):
    row = ", ".join("(void *)u%d" % j for j in range(i, min(i + 8, N_SLOTS)))
    out.append("    %s," % row)
out.append("};")
out.append("")
out.append("#endif")

open(sys.argv[1], "w").write("\n".join(out) + "\n")
print("wrote %s (%d slots)" % (sys.argv[1], N_SLOTS))
