#!/usr/bin/env python3
"""Generate gles_stubs.h: one thunk per dispatch slot, plus the default table.

Every slot needs a real function pointer. OpenGLES.framework's trampolines load
blindly from the table -- there is no null check anywhere in them -- so a slot we
leave at zero is not "unimplemented", it is a branch to address 0 the first time
an app touches it. Filling all 822 entries with a thunk that reports itself and
returns 0 turns "we do not implement that yet" from a crash into a log line.

Each thunk takes only the GC. Extra arguments the caller passed in r1-r3 or on
the stack are simply ignored, which is safe under AAPCS: the caller cleans up
its own stack arguments.
"""
import os
import re
import subprocess
import sys

# X+0x10 .. X+0xCE8 is the dispatch table, so 0xCD8/4 entries.
N_SLOTS = (0xCE8 - 0x10) // 4

TABLE_BASE = 0x10
GC_OFF = 0xc      # ldr r0, [r3, #0xc] -- the GC, not a table entry
TSD_OFF = 0xc0    # ldr r3, [r3, #0xc0] -- the per-thread engine block


def emit_map(out_path):
    """Recover slot->name by disassembling the armv6 OpenGLES trampolines.

    Each _gl* entry point loads its target out of the engine block with a
    single `ldr {r12,pc}, [rN, #off]`; the slot is (off - 0x10) / 4.
    """
    sdk = os.environ.get("ARMV6_SDK",
                         os.path.expanduser("~/Downloads/OldSDK/iPhoneOS3.1.3.sdk"))
    fw = os.path.join(sdk, "System/Library/Frameworks/OpenGLES.framework/OpenGLES")
    if not os.path.exists(fw):
        sys.exit("no OpenGLES at %s (set ARMV6_SDK)" % fw)

    dis = subprocess.run(["otool", "-arch", "armv6", "-tV", fw],
                         capture_output=True, text=True, check=True).stdout

    label = re.compile(r"^_(gl\w+):")
    # The tail-call target register is not fixed (r12, pc, r2, ... all appear),
    # so accept any destination and reject the two known non-table offsets.
    ldr = re.compile(r"\bldr\w*\s+\w+,\s*\[r\d+,\s*#(0x[0-9a-f]+)\]")

    name, cands, hits = None, [], {}
    def flush():
        if name and cands:
            hits.setdefault(name, set()).update(cands)
    for line in dis.splitlines():
        m = label.match(line)
        if m:
            flush()
            name, cands = m.group(1), []
            continue
        if name is None:
            continue
        if not line.startswith("0"):   # next symbol (non-gl) ends the block
            flush()
            name, cands = None, []
            continue
        m = ldr.search(line)
        if m:
            off = int(m.group(1), 16)
            if off not in (GC_OFF, TSD_OFF) and TABLE_BASE <= off < 0x10 + N_SLOTS * 4:
                cands.append(off)
    flush()

    slots = {}
    for n, offs in hits.items():
        if len(offs) != 1:
            print("skip %s: ambiguous offsets %s" % (n, sorted(map(hex, offs))),
                  file=sys.stderr)
            continue
        slots[n] = (offs.pop() - TABLE_BASE) // 4

    validate(slots)

    lines = ["# slot  glFunctionName -- generated by genstubs.py --emit-map",
             "# from %s" % fw]
    lines += ["%d %s" % (s, n) for n, s in sorted(slots.items(), key=lambda kv: (kv[1], kv[0]))]
    open(out_path, "w").write("\n".join(lines) + "\n")
    print("wrote %s (%d names, %d distinct slots)"
          % (out_path, len(slots), len(set(slots.values()))))


def validate(slots):
    """The map must reproduce every GLES_SLOT_* in the host header exactly."""
    hdr = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "../../include/hw/arm/guest-services/gles.h")
    known = dict(re.findall(r"#define GLES_SLOT_(\w+)\s+(\d+)", open(hdr).read()))
    if not known:
        sys.exit("no GLES_SLOT_* found in %s -- cannot self-validate" % hdr)

    # GLES_SLOT_FOO -> the gl names that could have produced it (glFoo, glFooOES...)
    by_slot = {}
    for n, s in slots.items():
        by_slot.setdefault(s, []).append(n)

    def subseq(short, long):
        it = iter(long)
        return all(c in it for c in short)

    bad = []
    for macro, want in sorted(known.items(), key=lambda kv: int(kv[1])):
        want = int(want)
        # Macro names are abbreviated (GET_RB_PARAMETERIV for
        # glGetRenderbufferParameteriv), so match as a subsequence rather than
        # equality -- still tight enough that a wrong function never passes.
        flat = macro.replace("_", "").lower()
        got = [n for n in by_slot.get(want, []) if subseq(flat, n[2:].lower())]
        if not by_slot.get(want):
            bad.append("GLES_SLOT_%s=%d: no trampoline maps to that slot" % (macro, want))
        elif not got:
            bad.append("GLES_SLOT_%s=%d: slot holds %s, name mismatch"
                       % (macro, want, by_slot[want]))
    if bad:
        sys.exit("SELF-VALIDATION FAILED (%d):\n  %s" % (len(bad), "\n  ".join(bad)))
    print("self-validation OK: all %d GLES_SLOT_* reproduced" % len(known))


if len(sys.argv) > 2 and sys.argv[1] == "--emit-map":
    emit_map(sys.argv[2])
    sys.exit(0)

out = ["/* Generated by genstubs.py -- do not edit. */",
       "#ifndef GLES_STUBS_H",
       "#define GLES_STUBS_H",
       "",
       "extern int gles_unimpl(unsigned slot);",
       ""]

for i in range(N_SLOTS):
    out.append("static int u%d(void *gc) { (void)gc; return gles_unimpl(%d); }" % (i, i))

out.append("")
out.append("#define GLES_N_SLOTS %d" % N_SLOTS)
out.append("static void *const gles_default_table[GLES_N_SLOTS] = {")
for i in range(0, N_SLOTS, 8):
    row = ", ".join("(void *)u%d" % j for j in range(i, min(i + 8, N_SLOTS)))
    out.append("    %s," % row)
out.append("};")
out.append("")
out.append("#endif")

open(sys.argv[1], "w").write("\n".join(out) + "\n")
print("wrote %s (%d slots)" % (sys.argv[1], N_SLOTS))
