#!/usr/bin/env python3
"""Generate gles_stubs.h: one stub per possible dispatch slot, for the slots the shim cannot name.

Every slot of the framework's table needs a real function pointer. OpenGLES's trampolines load
blindly from the table -- there is no null check anywhere in them -- so a slot left at zero is a
branch to address 0 the first time an app touches it. A slot whose dispatch field the name table
(include/hw/arm/guest-services/gles-names.h) does not know gets stub N, which reports itself by
slot (mbxshim's gles_unknown_slot names the field) and returns 0. Named slots never come here:
they get a forwarder or a by-name stub from the table.

Each stub takes only the GC. Extra arguments the caller passed in r1-r3 or on the stack are
simply ignored, which is safe under AAPCS: the caller cleans up its own stack arguments.

    genstubs.py OUT.h
    genstubs.py --emit-map slotmap.txt   (research: slot -> name from the 3.1.3 SDK's trampolines)
"""
import os
import re
import subprocess
import sys

# Room for every layout seen (822, 826, 841 slots) and then some; GLESCreateGC and glishim refuse more.
N_SLOTS = 1024

TABLE_BASE = 0x10
GC_OFF = 0xc      # ldr r0, [r3, #0xc] -- the GC, not a table entry
TSD_OFF = 0xc0    # ldr r3, [r3, #0xc0] -- the per-thread engine block


def emit_map(out_path):
    """Recover slot->name by disassembling the armv6 OpenGLES trampolines.

    Each _gl* entry point loads its target out of the engine block with a
    single `ldr {r12,pc}, [rN, #off]`; the slot is (off - 0x10) / 4.
    """
    sdk = os.environ.get("ARMV6_SDK",
                         os.path.expanduser("~/Downloads/OldSDK/iPhoneOS3.1.3.sdk"))
    fw = os.path.join(sdk, "System/Library/Frameworks/OpenGLES.framework/OpenGLES")
    if not os.path.exists(fw):
        sys.exit("no OpenGLES at %s (set ARMV6_SDK)" % fw)

    dis = subprocess.run(["otool", "-arch", "armv6", "-tV", fw],
                         capture_output=True, text=True, check=True).stdout

    label = re.compile(r"^_(gl\w+):")
    # The tail-call target register is not fixed (r12, pc, r2, ... all appear),
    # so accept any destination and reject the two known non-table offsets.
    ldr = re.compile(r"\bldr\w*\s+\w+,\s*\[r\d+,\s*#(0x[0-9a-f]+)\]")

    name, cands, hits = None, [], {}
    def flush():
        if name and cands:
            hits.setdefault(name, set()).update(cands)
    for line in dis.splitlines():
        m = label.match(line)
        if m:
            flush()
            name, cands = m.group(1), []
            continue
        if name is None:
            continue
        if not line.startswith("0"):   # next symbol (non-gl) ends the block
            flush()
            name, cands = None, []
            continue
        m = ldr.search(line)
        if m:
            off = int(m.group(1), 16)
            if off not in (GC_OFF, TSD_OFF) and TABLE_BASE <= off < 0x10 + 822 * 4:
                cands.append(off)
    flush()

    slots = {}
    for n, offs in hits.items():
        if len(offs) != 1:
            print("skip %s: ambiguous offsets %s" % (n, sorted(map(hex, offs))),
                  file=sys.stderr)
            continue
        slots[n] = (offs.pop() - TABLE_BASE) // 4

    lines = ["# slot  glFunctionName -- generated by genstubs.py --emit-map",
             "# from %s" % fw]
    lines += ["%d %s" % (s, n) for n, s in sorted(slots.items(), key=lambda kv: (kv[1], kv[0]))]
    open(out_path, "w").write("\n".join(lines) + "\n")
    print("wrote %s (%d names, %d distinct slots)"
          % (out_path, len(slots), len(set(slots.values()))))


if len(sys.argv) > 2 and sys.argv[1] == "--emit-map":
    emit_map(sys.argv[2])
    sys.exit(0)

out = ["/* Generated by genstubs.py -- do not edit. */",
       "#ifndef GLES_STUBS_H",
       "#define GLES_STUBS_H",
       "",
       "static int gles_unknown_slot(unsigned slot);",
       ""]
for i in range(N_SLOTS):
    out.append("static int u%d(void *gc) { (void)gc; return gles_unknown_slot(%d); }" % (i, i))
out.append("")
out.append("#define GLES_MAX_SLOTS %d" % N_SLOTS)
out.append("static void *const gles_unknown_table[GLES_MAX_SLOTS] = {")
for i in range(0, N_SLOTS, 8):
    out.append("    %s," % ", ".join("(void *)u%d" % j for j in range(i, min(i + 8, N_SLOTS))))
out.append("};")
out.append("")
out.append("#endif")

open(sys.argv[1], "w").write("\n".join(out) + "\n")
print("wrote %s (%d slots)" % (sys.argv[1], N_SLOTS))
