#!/usr/bin/env python3
"""The 1.x/2.x OpenGLES export set: the names ARE the ABI there (the framework is the IMG driver itself,
no dispatch table), so the replacement exports exactly the firmware's own names.

    gles2x_exports.py scan OPENGLES > LIST     the stock binary's exported symbols, one per line (read
                                               from its classic symbol table; no Apple bytes are kept)
    gles2x_exports.py gen LIST NAMES.H OUTDIR  OUTDIR/gles2x_exports.h: one GLES2X_FWD(export, row) per gl*
                                               export, routed to the gles-names.h row of that name or of
                                               its un-suffixed spelling (1.x/2.x export the FBO set, the
                                               mapbuffer set and glBlendEquation as ...OES; the row keeps
                                               the plain name); OUTDIR/gles2x.exp, ld's
                                               -exported_symbols_list, so nothing else is exported
    gles2x_exports.py check LIST OPENGLES      exit 1 unless the stock binary exports exactly LIST
                                               (the preparer runs this before hooking the framework)

A gl* name with no row and not written by hand in gles2x.c (HAND) fails the build: a new firmware's
name is a new row in gles-names.h, never a silent gap.
"""
import os, re, struct, sys

# gl* exports gles2x.c implements itself, over the core's existing entry points
HAND = {"glTexImageCoreSurfaceAPPLE", "glFinishTextureAPPLE", "glGetString",
        "glVertexAttribPointerARB"}   # 1.x only: no ES 1.1 row, a counted refusal


def scan(path):
    """Defined external symbols of a thin (or the armv6 slice of a fat) 32-bit Mach-O, without the _."""
    b = open(path, "rb").read()
    if struct.unpack_from(">I", b)[0] == 0xCAFEBABE:
        for i in range(struct.unpack_from(">I", b, 4)[0]):
            cpu, sub, off, size, _ = struct.unpack_from(">iiIII", b, 8 + 20 * i)
            if cpu == 12:
                b = b[off:off + size]
                break
    if struct.unpack_from("<I", b)[0] != 0xFEEDFACE:
        raise SystemExit("%s: not a 32-bit Mach-O" % path)
    ncmds, off, symtab, dysym = struct.unpack_from("<I", b, 16)[0], 28, None, None
    for _ in range(ncmds):
        cmd, size = struct.unpack_from("<II", b, off)
        if cmd == 2:
            symtab = struct.unpack_from("<4I", b, off + 8)
        elif cmd == 0xB:
            dysym = struct.unpack_from("<18I", b, off + 8)
        off += size
    symoff, nsyms, stroff, _ = symtab
    first, count = (dysym[2], dysym[3]) if dysym else (0, nsyms)
    names = []
    for k in range(first, first + count):
        strx, ntype = struct.unpack_from("<IB", b, symoff + 12 * k)
        if ntype & 0x01 and ntype & 0x0E:              # N_EXT, defined
            n = b[stroff + strx:b.index(0, stroff + strx)].decode()
            names.append(n[1:] if n.startswith("_") else n)
    return sorted(names)


def read_list(path):
    return [l.strip() for l in open(path) if l.strip() and not l.startswith("#")]


def rows(names_h):
    return {m.group(1) for m in re.finditer(r"^GLES_FN\((\w+),", open(names_h).read(), re.M)}


def gen(listfile, names_h, out):
    have, fwd, missing = rows(names_h), [], []
    names = read_list(listfile)
    for n in names:
        if not n.startswith("gl") or n in HAND:
            continue
        row = n if n in have else n[:-3] if n.endswith("OES") and n[:-3] in have else None
        if row is None:
            missing.append(n)
        else:
            fwd.append((n, row))
    if missing:
        raise SystemExit("gles2x: no gles-names.h row for %s" % ", ".join(missing))
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "gles2x_exports.h"), "w") as f:
        f.write("/* Generated by gles2x_exports.py from %s: GLES2X_FWD(export, gles-names.h row) */\n"
                % os.path.basename(listfile))
        f.writelines("GLES2X_FWD(%s, %s)\n" % p for p in fwd)
    with open(os.path.join(out, "gles2x.exp"), "w") as f:
        f.writelines("_%s\n" % n for n in names)
    print("gles2x: %d exports, %d gl* forwarded by name (%d under an OES spelling), %d by hand"
          % (len(names), len(fwd), sum(1 for n, r in fwd if n != r), len(HAND & set(names))))


def main():
    a = sys.argv[1:]
    if a[:1] == ["scan"] and len(a) == 2:
        sys.stdout.writelines(n + "\n" for n in scan(a[1]))
    elif a[:1] == ["gen"] and len(a) == 4:
        gen(*a[1:])
    elif a[:1] == ["check"] and len(a) == 3:
        want, got = set(read_list(a[1])), set(scan(a[2]))
        if want != got:
            sys.exit("%s exports differ from %s: missing %s, extra %s" % (
                a[2], a[1], sorted(want - got)[:8], sorted(got - want)[:8]))
        print("%s: %d exports, as %s" % (a[2], len(got), a[1]))
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
