#!/bin/sh
# The 1.x/2.x OpenGLES export set: the names ARE the ABI there (the framework is the IMG driver itself, no dispatch
# table), so the replacement exports exactly the firmware's own names.
#
#   gles-exports.sh LIST NAMES.H OUTDIR
#
# LIST (opengles-1x.exports, ../gles-public/opengles.exports) is the stock binaries' exported symbols, one per line.
# OUTDIR/gles2x_exports.h gets one GLES2X_FWD(export, row) per gl* export, routed to the gles-names.h row of that
# name, of its alias, or of its un-suffixed spelling (1.x/2.x export the FBO set, the mapbuffer set and
# glBlendEquation as ...OES; the row keeps the plain name); OUTDIR/gles2x.exp is ld's -exported_symbols_list, so
# nothing else is exported. A gl* name with no row and not written by hand in the front ends fails the build: a new
# firmware's name is a new row in gles-names.h, never a silent gap.
set -eu
[ $# -eq 3 ] || { echo "usage: $0 LIST NAMES.H OUTDIR" >&2; exit 2; }
mkdir -p "$3"
awk -v list="$(basename "$1")" -v out="$3" '
    # gl* exports the front ends implement themselves, over the core entry points
    BEGIN { split("glTexImageCoreSurfaceAPPLE glFinishTextureAPPLE glGetString glVertexAttribPointerARB", hl, " ")
            for (i in hl) hand[hl[i]] = 1
            # exports whose row is another name: the firmware trampolines for both load the same dispatch field
            alias["glDeleteProgram"] = "glDeleteShader" }
    FNR == NR { if (match($0, /^GLES_FN\([A-Za-z0-9_]+,/)) have[substr($0, 9, RLENGTH - 9)] = 1; next }
    function strip(n, s) { return substr(n, 1, length(n) - length(s)) }
    function ends(n, s) { return length(n) > length(s) && substr(n, length(n) - length(s) + 1) == s }
    function row(n,    s, i) {
        if (n in have) return n
        if ((n in alias) && (alias[n] in have)) return alias[n]
        split("OES EXT", s, " ")
        for (i = 1; i <= 2; i++) if (ends(n, s[i]) && (strip(n, s[i]) in have)) return strip(n, s[i])
        # 5.0 beta 1 (9A5220p) exports the EXT set as ...APPLE: those take the row of the ...EXT name
        if (ends(n, "APPLE")) return row(strip(n, "APPLE") "EXT")
        # 7.x ES 3.0 core names: the row of the extension (glFenceSync -> ...APPLE)
        if (!ends(n, "APPLE") && !ends(n, "EXT") && !ends(n, "OES")) {
            if ((n "APPLE") in have) return n "APPLE"
            if ((n "EXT") in have) return n "EXT"
            if ((n "OES") in have) return n "OES"
        }
        return ""
    }
    /^#/ { next }
    { gsub(/^[ \t]+|[ \t\r]+$/, ""); if ($0 == "") next
      names[++count] = $0
      if ($0 !~ /^gl/ || ($0 in hand)) next
      r = row($0)
      if (r == "") missing = missing (missing == "" ? "" : ", ") $0
      else fwd[++nfwd] = "GLES2X_FWD(" $0 ", " r ")" }
    END {
        if (missing != "") { print "gles-exports: no gles-names.h row for " missing > "/dev/stderr"; exit 1 }
        h = out "/gles2x_exports.h"; e = out "/gles2x.exp"
        print "/* Generated by gles-exports.sh from " list ": GLES2X_FWD(export, gles-names.h row) */" > h
        for (i = 1; i <= nfwd; i++) print fwd[i] > h
        for (i = 1; i <= count; i++) print "_" names[i] > e
    }' "$2" "$1"
