/* Import staged music or video through the 7E18 MusicLibrary service. The service owns
 * the item. SQLite below is read-only, for retry reconciliation; the item's year, which
 * the purchase-folder insert has no property for, goes through MusicLibrary's own connection.
 * There is no CRT in these ARMv6 executables; see armv6-toolchain/README.md.
 * -DITMEDIA_HOST_CHECK builds the metadata mapping alone for the Mac, so offline checks
 * run this file's mapping rather than a copy of it. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <math.h>
#include <dlfcn.h>
#include <sqlite3.h>

#define MEDIA "/var/mobile/Media/"
#define LIBRARY MEDIA "iTunes_Control/iTunes/iTunes Library.itlp/"
typedef void *ID;
static ID (*getclass)(const char *), (*selector)(const char *);
static void *send;
#define CALL(ret,args) ((ret (*)args)send)
static ID m0(ID o, const char *s) { return CALL(ID,(ID,ID))(o,selector(s)); }
static ID m1(ID o, const char *s, ID a) { return CALL(ID,(ID,ID,ID))(o,selector(s),a); }
static ID number(unsigned value) {
    return CALL(ID,(ID,ID,unsigned))(getclass("NSNumber"),selector("numberWithUnsignedInt:"),value);
}
static ID string(const char *s) {
    return CALL(ID,(ID,ID,const char *))(getclass("NSString"),selector("stringWithUTF8String:"),s);
}
static const char *utf8(ID o) { return CALL(const char *,(ID,ID))(o,selector("UTF8String")); }
static int is_class(ID o, const char *name) {
    return o && CALL(int,(ID,ID,ID))(o,selector("isKindOfClass:"),getclass(name));
}
static ID field(ID o, const char *key) { return m1(o,"objectForKey:",string(key)); }
static void set(ID o, const char *key, ID value) {
    CALL(void,(ID,ID,ID,ID))(o,selector("setObject:forKey:"),value,string(key));
}
static void fail(const char *reason) {
    fprintf(stderr,"itmedia: %s\n",reason);
    _exit(1);
}

/* Components are generated by the host. Never let metadata select a path
 * outside the dedicated staging tree, including through symlinks. */
static int component(const char *s) {
    size_t n = s ? strlen(s) : 0;
    if (!n || n > 128 || s[0] == '.') return 0;
    for (; *s; ++s) {
        if (!((*s >= 'a' && *s <= 'z') || (*s >= 'A' && *s <= 'Z') ||
              (*s >= '0' && *s <= '9') || *s == '-' || *s == '_' || *s == '.')) return 0;
    }
    return 1;
}
static void regular_path(const char *path, int directory) {
    struct stat st;
    if (lstat(path,&st) || (directory ? !S_ISDIR(st.st_mode) : !S_ISREG(st.st_mode)))
        fail("staged media path is missing or is not a regular file/directory");
    if (!directory && (st.st_size <= 0 || st.st_size > 1024LL*1024*1024))
        fail("staged file size is outside 1 byte..1 GiB");
}

/* Purchased items' artwork lives in an ArtworkCache keyed by the item's store ID
 * (MLMusicLibrary_SQL reads the "%lu" of artworkDBRecordID, which the insert takes
 * from itemId, from Purchases/MobileArtworkDB). A nonzero ID from the staging ID's
 * first 31 bits; staging IDs are content hashes, so a retry keeps its key. */
static unsigned artwork_key(const char *staging) {
    char prefix[9] = {0};
    strncpy(prefix,staging,8);
    unsigned key = (unsigned)strtoul(prefix,NULL,16) & 0x7fffffff;
    return key ? key : 1;
}

/* Validate the host's metadata and build MusicLibrary's purchase-folder item properties
 * (7E18 -[MLMusicLibrary_SQL insertItemFromPurchaseFolder:withItemProperties:] keys).
 * Sets *artwork to the staged cover's file name and *year when present. */
static ID item_properties(ID input, const char *staging, const char **filename_out,
                          const char **artwork, unsigned *year) {
    ID filename_value = field(input,"filename");
    if (!is_class(filename_value,"NSString")) fail("filename must be a string");
    const char *filename = utf8(filename_value);
    if (!component(filename)) fail("invalid filename");
    ID kind_value = field(input,"kind");
    if (kind_value && !is_class(kind_value,"NSString")) fail("kind must be a string");
    const char *kind = kind_value ? utf8(kind_value) : "song";
    if (!kind || (strcmp(kind,"song") && strcmp(kind,"feature-movie")))
        fail("kind must be song or feature-movie");
    int movie = !strcmp(kind,"feature-movie");
    const char *extension = strrchr(filename,'.');
    if (!extension || (movie
        ? (strcmp(extension,".m4v") && strcmp(extension,".mp4") && strcmp(extension,".mov"))
        : (strcmp(extension,".m4a") && strcmp(extension,".mp3") && strcmp(extension,".wav"))))
        fail("expected m4a/mp3/wav for song or m4v/mp4/mov for feature-movie");

    ID props = m0(getclass("NSMutableDictionary"),"dictionary");
    const char *source[] = {"title","artist","album","album_artist","composer","genre"};
    const char *target[] = {"itemName","artistName","playlistName","playlistArtistName","composerName","genre"};
    for (unsigned i=0; i<sizeof(source)/sizeof(*source); ++i) {
        ID value = field(input,source[i]);
        if (!value && i) continue;
        if (!is_class(value,"NSString")) fail("text metadata must be strings");
        const char *text = utf8(value);
        if (!text || strlen(text)>4096 || (!i && !*text)) fail("invalid or oversized media metadata");
        set(props,target[i],value);
    }
    /* UInt16 in MusicLibrary's purchase dictionary reader. */
    const char *counts[] = {"track_number","track_count","disc_number","disc_count"};
    const char *count_target[] = {"trackNumber","trackCount","discNumber","discCount"};
    for (unsigned i=0; i<4; ++i) {
        ID value = field(input,counts[i]);
        if (!value) continue;
        int n = is_class(value,"NSNumber") ? CALL(int,(ID,ID))(value,selector("intValue")) : 0;
        if (n < 1 || n > 65535) fail("track and disc numbers must be 1..65535");
        set(props,count_target[i],number((unsigned)n));
    }
    ID compilation = field(input,"compilation");
    if (compilation) {
        if (!is_class(compilation,"NSNumber")) fail("compilation must be a boolean");
        set(props,"compilation",
            CALL(ID,(ID,ID,int))(getclass("NSNumber"),selector("numberWithBool:"),
                                 CALL(signed char,(ID,ID))(compilation,selector("boolValue")) != 0));
    }
    *year = 0;
    ID year_value = field(input,"year");
    if (year_value) {
        int y = is_class(year_value,"NSNumber") ? CALL(int,(ID,ID))(year_value,selector("intValue")) : 0;
        if (y < 1 || y > 9999) fail("year must be 1..9999");
        *year = (unsigned)y;
    }
    ID duration = field(input,"duration_ms");
    if (!is_class(duration,"NSNumber")) fail("duration_ms must be numeric");
    double ms = CALL(double,(ID,ID))(duration,selector("doubleValue"));
    if (!isfinite(ms) || ms <= 0 || ms > 86400000) fail("duration must be within one day");
    set(props,"duration",duration);
    /* 7E18 ITMediaKindFromOTAMediaKindString maps feature-movie to kind 2
     * and sets has_video. Let MusicLibrary populate every related field. */
    set(props,"kind",string(kind));
    *artwork = NULL;
    ID artwork_value = field(input,"artwork");
    if (artwork_value) {
        if (!is_class(artwork_value,"NSString") || !component(utf8(artwork_value)) ||
            !strcmp(utf8(artwork_value),filename)) fail("invalid artwork filename");
        *artwork = utf8(artwork_value);
        set(props,"itemId",number(artwork_key(staging)));
    }
    ID download = m0(getclass("NSMutableDictionary"),"dictionary");
    set(download,"mediaAssetFilename",filename_value);
    set(props,"com.apple.iTunesStore.downloadInfo",download);
    *filename_out = filename;
    return props;
}

static void load_foundation(void) {
    void *objc = dlopen("/usr/lib/libobjc.A.dylib",RTLD_NOW);
    if (!objc) fail("cannot load Objective-C runtime");
    getclass = dlsym(objc,"objc_getClass");
    selector = dlsym(objc,"sel_registerName");
    send = dlsym(objc,"objc_msgSend");
    if (!getclass || !selector || !send ||
        !dlopen("/System/Library/Frameworks/Foundation.framework/Foundation",RTLD_NOW))
        fail("cannot load Foundation");
}

static ID read_metadata(const char *path) {
    regular_path(path,0);
    struct stat metadata_stat;
    if (stat(path,&metadata_stat) || metadata_stat.st_size > 65536) fail("metadata exceeds 64 KiB");
    ID input = m1(getclass("NSDictionary"),"dictionaryWithContentsOfFile:",string(path));
    if (!is_class(input,"NSDictionary")) fail("metadata must be a dictionary plist");
    return input;
}

#ifdef ITMEDIA_HOST_CHECK
/* itmedia-host metadata.plist staging-id out.plist: what the guest would hand
 * MusicLibrary (properties), the ArtworkCache (artwork, artworkKey) and the year UPDATE. */
int main(int argc, char **argv) {
    if (argc != 4 || !component(argv[2])) fail("usage: itmedia-host metadata.plist staging-id out.plist");
    load_foundation();
    const char *filename, *artwork;
    unsigned year;
    ID props = item_properties(read_metadata(argv[1]),argv[2],&filename,&artwork,&year);
    ID out = m0(getclass("NSMutableDictionary"),"dictionary");
    set(out,"properties",props);
    if (artwork) {
        set(out,"artwork",string(artwork));
        char key[16];
        snprintf(key,sizeof(key),"%u",artwork_key(argv[2]));
        set(out,"artworkKey",string(key));
    }
    if (year) set(out,"year",number(year));
    return CALL(signed char,(ID,ID,ID,signed char))(out,selector("writeToFile:atomically:"),string(argv[3]),1) ? 0 : 1;
}
#else
static __typeof__(sqlite3_open_v2) *sql_open;
static __typeof__(sqlite3_busy_timeout) *sql_timeout;
static __typeof__(sqlite3_exec) *sql_exec;
static __typeof__(sqlite3_prepare_v2) *sql_prepare;
static __typeof__(sqlite3_bind_text) *sql_bind;
static __typeof__(sqlite3_column_int64) *sql_column_int64;
static __typeof__(sqlite3_step) *sql_step;
static __typeof__(sqlite3_finalize) *sql_finalize;
static __typeof__(sqlite3_close) *sql_close;
static __typeof__(sqlite3_errmsg) *sql_error;
static void database_failure(sqlite3 *db, const char *reason) {
    fprintf(stderr,"itmedia: %s: %s\n",reason,db ? sql_error(db) : "no connection");
    _exit(1);
}

/* The item pid of existing media at the exact immutable staged location, or 0.
 * Fail closed on a query error: an uncertain previous import must not replay. */
static sqlite3_int64 existing(const char *folder, const char *filename) {
    sqlite3 *db = NULL;
    sqlite3_stmt *stmt = NULL;
    sqlite3_int64 found;
    if (sql_open(LIBRARY "Library.itdb",&db,SQLITE_OPEN_READONLY,NULL) != SQLITE_OK)
        database_failure(db,"cannot inspect music library");
    sql_timeout(db,5000);
    if (sql_exec(db,"ATTACH DATABASE '" LIBRARY "Locations.itdb' AS loc",NULL,NULL,NULL) != SQLITE_OK)
        database_failure(db,"cannot inspect media locations");
    /* Music creates indexes with private sort collations on its first launch.
     * This identity query needs none of them. Do not supply a fake collation
     * or let the old SQLite planner choose those indexes after a reboot. */
    const char *sql = "SELECT item.pid FROM item NOT INDEXED JOIN loc.location l ON l.item_pid=item.pid "
                      "JOIN loc.base_location b ON b.id=l.base_location_id "
                      "WHERE b.path=? AND l.location=? LIMIT 1";
    if (sql_prepare(db,sql,-1,&stmt,NULL) != SQLITE_OK ||
        sql_bind(stmt,1,folder,-1,SQLITE_TRANSIENT) != SQLITE_OK ||
        sql_bind(stmt,2,filename,-1,SQLITE_TRANSIENT) != SQLITE_OK)
        database_failure(db,"cannot query music library");
    int rc = sql_step(stmt);
    if (rc != SQLITE_ROW && rc != SQLITE_DONE) database_failure(db,"music library query failed");
    found = rc == SQLITE_ROW ? sql_column_int64(stmt,0) : 0;
    sql_finalize(stmt);
    sql_close(db);
    return found;
}

/* Render the staged cover into Purchases/MobileArtworkDB with the device's own
 * AlbumArt formats (lockdown's com.apple.mobile.iTunes domain), under the key
 * MusicLibrary looks up for this item. */
static void import_artwork(const char *path, const char *staging) {
    regular_path(path,0);
    struct stat st;
    if (stat(path,&st) || st.st_size > 16*1024*1024) fail("artwork exceeds 16 MiB");
    void *cache = dlopen("/System/Library/PrivateFrameworks/ArtworkCache.framework/ArtworkCache",RTLD_NOW);
    unsigned char (*process)(ID,ID,ID,ID) = cache ? dlsym(cache,"ArtworkCache_ProcessArtworkData") : NULL;
    if (!process) fail("ArtworkCache is unavailable");
    mkdir(MEDIA "Purchases",0755);
    mkdir(MEDIA "Purchases/MobileArtworkDB",0755);
    regular_path(MEDIA "Purchases/MobileArtworkDB",1);
    ID data = m1(getclass("NSData"),"dataWithContentsOfFile:",string(path));
    ID directory = m1(getclass("NSURL"),"fileURLWithPath:",string(MEDIA "Purchases/MobileArtworkDB"));
    char key[16];
    snprintf(key,sizeof(key),"%u",artwork_key(staging));
    if (!data || !directory || !process(directory,string(key),string("AlbumArt"),data))
        fail("artwork was not stored; retain staged media for reconciliation");
}

/* Through MusicLibrary's own writer connection: it opens the library with its own
 * SQLite VFS, so a second plain connection is read-only. No 7E18 trigger or index
 * covers item.year, and the purchase-folder insert has no property for it. */
static void record_year(sqlite3_int64 pid, unsigned year) {
    void *support = dlopen("/System/Library/PrivateFrameworks/AppSupport.framework/AppSupport",RTLD_NOW);
    void *library = dlopen("/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary",RTLD_NOW);
    void *(*shared_store)(void) = library ? dlsym(library,"MLSDBGetSharedRecordStore") : NULL;
    void *(*store_database)(void *) = support ? dlsym(support,"CPRecordStoreGetDatabase") : NULL;
    void *(*for_writing)(void *) = support ? dlsym(support,"CPSqliteDatabaseConnectionForWriting") : NULL;
    int (*perform)(void *,ID) = support ? dlsym(support,"CPSqliteConnectionPerformSQL") : NULL;
    if (!shared_store || !store_database || !for_writing || !perform) fail("MusicLibrary database API unavailable");
    void *connection = for_writing(store_database(shared_store()));
    char sql[96];
    snprintf(sql,sizeof(sql),"UPDATE item SET year=%u WHERE pid=%lld",year,(long long)pid);
    int rc = connection ? perform(connection,string(sql)) : SQLITE_ERROR;
    if (rc != SQLITE_DONE && rc != SQLITE_OK) fail("year not recorded; retain staged media for reconciliation");
}

__attribute__((naked)) void _start(void) {
    __asm__ volatile("ldr r0, [sp]\n\tadd r1, sp, #4\n\tb _main");
}
int main(int argc, char **argv) {
    if (argc != 3 || !component(argv[2]))
        fail("usage: itmedia metadata.plist staging-id");
    if (getuid() == 0 && (setgid(501) || setuid(501))) fail("cannot become mobile");
    if (getuid() != 501) fail("must run as mobile or root");
    setenv("HOME","/var/mobile",1);
    load_foundation();
    ID pool = m0(m0(getclass("NSAutoreleasePool"),"alloc"),"init");
    ID version = m1(getclass("NSDictionary"),"dictionaryWithContentsOfFile:",
                    string("/System/Library/CoreServices/SystemVersion.plist"));
    const char *build = utf8(field(version,"ProductBuildVersion"));
    if (!build || strcmp(build,"7E18")) fail("unsupported firmware; expected 7E18");
    const char *filename, *artwork;
    unsigned year;
    ID props = item_properties(read_metadata(argv[1]),argv[2],&filename,&artwork,&year);
    char folder[160], path[512];
    snprintf(folder,sizeof(folder),"LightTouch/%s",argv[2]);
    regular_path(MEDIA "LightTouch",1);
    snprintf(path,sizeof(path),MEDIA "%s",folder);
    regular_path(path,1);
    snprintf(path,sizeof(path),MEDIA "%s/%s",folder,filename);
    regular_path(path,0);
    if (access(path,R_OK)) fail("staged media is not readable by mobile");
    char artwork_path[512];
    if (artwork) snprintf(artwork_path,sizeof(artwork_path),MEDIA "%s/%s",folder,artwork);

    int lock = open(MEDIA "LightTouch/.import.lock",O_RDWR|O_CREAT|O_NOFOLLOW,0600);
    if (lock < 0 || flock(lock,LOCK_EX|LOCK_NB)) fail("another media import is running");
    if (!dlopen("/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary",RTLD_NOW))
        fail("cannot load MusicLibrary");
    void *sqlite = dlopen("/usr/lib/libsqlite3.dylib",RTLD_NOW);
    if (!sqlite) fail("cannot load SQLite for import reconciliation");
    sql_open = dlsym(sqlite,"sqlite3_open_v2");
    sql_timeout = dlsym(sqlite,"sqlite3_busy_timeout");
    sql_exec = dlsym(sqlite,"sqlite3_exec");
    sql_prepare = dlsym(sqlite,"sqlite3_prepare_v2");
    sql_bind = dlsym(sqlite,"sqlite3_bind_text");
    sql_column_int64 = dlsym(sqlite,"sqlite3_column_int64");
    sql_step = dlsym(sqlite,"sqlite3_step");
    sql_finalize = dlsym(sqlite,"sqlite3_finalize");
    sql_close = dlsym(sqlite,"sqlite3_close");
    sql_error = dlsym(sqlite,"sqlite3_errmsg");
    if (!sql_open || !sql_timeout || !sql_exec || !sql_prepare || !sql_bind ||
        !sql_column_int64 ||
        !sql_step || !sql_finalize || !sql_close || !sql_error) fail("SQLite API unavailable");
    ID library = m0(getclass("MusicLibrary"),"sharedMusicLibrary");
    const char *insert = "insertItemFromPurchaseFolder:withItemProperties:";
    if (!library || !CALL(int,(ID,ID,ID))(library,selector("respondsToSelector:"),selector(insert)))
        fail("MusicLibrary import service is unavailable");
    /* Before the item exists, so Music never shows it without its cover; a retry
     * re-renders under the same key. */
    if (artwork) import_artwork(artwork_path,argv[2]);
    sqlite3_int64 pid = existing(folder,filename);
    int was_present = pid != 0;
    if (!was_present) {
        ID result = CALL(ID,(ID,ID,ID,ID))(library,selector(insert),string(folder),props);
        if (!result) fail("MusicLibrary declined import; retain staged media for reconciliation");
        m0(getclass("MusicLibrary"),"commitAllDeferredWork");
        m0(getclass("MusicLibrary"),"flush");
        if (!(pid = existing(folder,filename))) fail("import not visible; retain staged media for reconciliation");
    }
    if (year) record_year(pid,year);
    /* Finish native post-sync sorting/index work before Music is launched.
     * Otherwise its SyncHelper starts that work itself and schedules a normal
     * terminateWithSuccess when the sync phase ends (7E18: 0x57bc4). */
    void *sync = dlopen("/System/Library/PrivateFrameworks/ITSync.framework/ITSync",RTLD_NOW);
    int (*postprocess)(ID,int) = sync ? dlsym(sync,"ITDBPrepServerPostProcessRun") : NULL;
    if (!postprocess || !postprocess(NULL,1))
        fail("music post-processing did not finish; retain staging for reconciliation");
    puts(was_present ? "already-imported" : "imported");
    fflush(stdout);
    m0(pool,"drain");
    close(lock);
    _exit(0);
}
#endif
