/* Import staged music or video through the 7E18 MusicLibrary service. The service owns
 * all database mutations. SQLite below is read-only, for retry reconciliation.
 * There is no CRT in these ARMv6 executables; see armv6-toolchain/README.md. */
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <math.h>
#include <dlfcn.h>
#include <sqlite3.h>

#define MEDIA "/var/mobile/Media/"
#define LIBRARY MEDIA "iTunes_Control/iTunes/iTunes Library.itlp/"
typedef void *ID;
static ID (*getclass)(const char *), (*selector)(const char *);
static void *send;
static __typeof__(sqlite3_open_v2) *sql_open;
static __typeof__(sqlite3_busy_timeout) *sql_timeout;
static __typeof__(sqlite3_exec) *sql_exec;
static __typeof__(sqlite3_prepare_v2) *sql_prepare;
static __typeof__(sqlite3_bind_text) *sql_bind;
static __typeof__(sqlite3_step) *sql_step;
static __typeof__(sqlite3_column_int64) *sql_column;
static __typeof__(sqlite3_finalize) *sql_finalize;
static __typeof__(sqlite3_close) *sql_close;
static __typeof__(sqlite3_errmsg) *sql_error;
#define CALL(ret,args) ((ret (*)args)send)
static ID m0(ID o, const char *s) { return CALL(ID,(ID,ID))(o,selector(s)); }
static ID m1(ID o, const char *s, ID a) { return CALL(ID,(ID,ID,ID))(o,selector(s),a); }
static ID string(const char *s) {
    return CALL(ID,(ID,ID,const char *))(getclass("NSString"),selector("stringWithUTF8String:"),s);
}
static const char *utf8(ID o) { return CALL(const char *,(ID,ID))(o,selector("UTF8String")); }
static int is_class(ID o, const char *name) {
    return o && CALL(int,(ID,ID,ID))(o,selector("isKindOfClass:"),getclass(name));
}
static ID field(ID o, const char *key) { return m1(o,"objectForKey:",string(key)); }
static void set(ID o, const char *key, ID value) {
    CALL(void,(ID,ID,ID,ID))(o,selector("setObject:forKey:"),value,string(key));
}
static void fail(const char *reason) {
    fprintf(stderr,"itmedia: %s\n",reason);
    _exit(1);
}
static void database_failure(sqlite3 *db, const char *reason) {
    fprintf(stderr,"itmedia: %s: %s\n",reason,db ? sql_error(db) : "no connection");
    _exit(1);
}

/* Components are generated by the host. Never let metadata select a path
 * outside the dedicated staging tree, including through symlinks. */
static int component(const char *s) {
    size_t n = s ? strlen(s) : 0;
    if (!n || n > 128 || s[0] == '.') return 0;
    for (; *s; ++s) {
        if (!((*s >= 'a' && *s <= 'z') || (*s >= 'A' && *s <= 'Z') ||
              (*s >= '0' && *s <= '9') || *s == '-' || *s == '_' || *s == '.')) return 0;
    }
    return 1;
}
static void regular_path(const char *path, int directory) {
    struct stat st;
    if (lstat(path,&st) || (directory ? !S_ISDIR(st.st_mode) : !S_ISREG(st.st_mode)))
        fail("staged media path is missing or is not a regular file/directory");
    if (!directory && (st.st_size <= 0 || st.st_size > 1024LL*1024*1024))
        fail("staged file size is outside 1 byte..1 GiB");
}

/* An old SQLite connection can retain the attached Locations schema while
 * Apple's sync service replaces its indexes. Reopen and reprepare only on
 * SQLITE_SCHEMA; every other error remains fatal, so uncertainty never replays
 * an import. These queries never mutate either database. */
static int read_query(const char *sql, const char *folder, const char *filename,
                      sqlite3_int64 *value) {
    for (unsigned attempt = 0; attempt < 3; ++attempt) {
        sqlite3 *db = NULL;
        sqlite3_stmt *stmt = NULL;
        int rc = sql_open(LIBRARY "Library.itdb",&db,SQLITE_OPEN_READONLY,NULL);
        if (rc == SQLITE_OK) {
            sql_timeout(db,5000);
            if (folder) rc = sql_exec(db,"ATTACH DATABASE '" LIBRARY "Locations.itdb' AS loc",NULL,NULL,NULL);
            if (rc == SQLITE_OK) rc = sql_prepare(db,sql,-1,&stmt,NULL);
            if (rc == SQLITE_OK && folder) rc = sql_bind(stmt,1,folder,-1,SQLITE_TRANSIENT);
            if (rc == SQLITE_OK && filename) rc = sql_bind(stmt,2,filename,-1,SQLITE_TRANSIENT);
            if (rc == SQLITE_OK) rc = sql_step(stmt);
        }
        if (rc != SQLITE_ROW && rc != SQLITE_DONE &&
            (rc != SQLITE_SCHEMA || attempt == 2))
            database_failure(db,"music library query failed");
        if (rc == SQLITE_ROW) *value = sql_column(stmt,0);
        sql_finalize(stmt);
        sql_close(db);
        if (rc != SQLITE_SCHEMA) return rc;
        usleep(50000);
    }
    fail("music library schema did not settle");
    return SQLITE_ERROR;
}

/* Return 1 for existing media at the exact immutable staged location.
 * Fail closed on a query error: an uncertain previous import must not replay. */
static int existing(const char *folder, const char *filename, unsigned *artwork_id) {
    /* Music creates indexes with private sort collations on its first launch.
     * This identity query needs none of them. Do not supply a fake collation
     * or let the old SQLite planner choose those indexes after a reboot. */
    const char *sql = "SELECT item.artwork_cache_id FROM item NOT INDEXED JOIN loc.location l ON l.item_pid=item.pid "
                      "JOIN loc.base_location b ON b.id=l.base_location_id "
                      "WHERE b.path=? AND l.location=? LIMIT 1";
    sqlite3_int64 value = 0;
    int found = read_query(sql,folder,filename,&value) == SQLITE_ROW;
    if (found && artwork_id) *artwork_id = (unsigned)value;
    return found;
}

/* ArtworkCache uses the purchase itemId as its string key. Choose an unused
 * ID from the native library under the import lock; only Apple writes either DB. */
static unsigned next_artwork_id(void) {
    sqlite3_int64 last = 0;
    if (read_query("SELECT COALESCE(MAX(artwork_cache_id),0) FROM item NOT INDEXED",NULL,NULL,&last) != SQLITE_ROW)
        fail("cannot allocate artwork ID");
    if (last < 0 || last >= 0xffffffffLL) fail("artwork ID space exhausted");
    return (unsigned)(last+1);
}
static void import_artwork(const char *folder, unsigned identifier) {
    char path[512], key[32];
    snprintf(path,sizeof(path),MEDIA "%s/artwork.jpg",folder);
    ID data = m1(getclass("NSData"),"dataWithContentsOfFile:",string(path));
    void *cache = dlopen("/System/Library/PrivateFrameworks/ArtworkCache.framework/ArtworkCache",RTLD_NOW);
    int (*process)(ID,ID,ID,ID) = cache ? dlsym(cache,"ArtworkCache_ProcessArtworkData") : NULL;
    ID *albums = cache ? dlsym(cache,"kArtworkCacheCategory_Albums") : NULL;
    if (!process || !albums || !*albums || !data) fail("artwork service unavailable");
    if (mkdir(MEDIA "Purchases",0755) && errno != EEXIST) fail("cannot create purchase artwork folder");
    regular_path(MEDIA "Purchases",1);
    if (mkdir(MEDIA "Purchases/MobileArtworkDB",0755) && errno != EEXIST) fail("cannot create artwork cache folder");
    regular_path(MEDIA "Purchases/MobileArtworkDB",1);
    ID url = m1(getclass("NSURL"),"fileURLWithPath:",string(MEDIA "Purchases/MobileArtworkDB"));
    snprintf(key,sizeof(key),"%u",identifier);
    if (!process(url,string(key),*albums,data)) fail("artwork processing failed; retain staging for reconciliation");
}

__attribute__((naked)) void _start(void) {
    __asm__ volatile("ldr r0, [sp]\n\tadd r1, sp, #4\n\tb _main");
}
int main(int argc, char **argv) {
    if (argc != 3 || !component(argv[2]))
        fail("usage: itmedia metadata.plist staging-id");
    if (getuid() == 0 && (setgid(501) || setuid(501))) fail("cannot become mobile");
    if (getuid() != 501) fail("must run as mobile or root");
    setenv("HOME","/var/mobile",1);
    void *objc = dlopen("/usr/lib/libobjc.A.dylib",RTLD_NOW);
    if (!objc) fail("cannot load Objective-C runtime");
    getclass = dlsym(objc,"objc_getClass");
    selector = dlsym(objc,"sel_registerName");
    send = dlsym(objc,"objc_msgSend");
    if (!getclass || !selector || !send ||
        !dlopen("/System/Library/Frameworks/Foundation.framework/Foundation",RTLD_NOW))
        fail("cannot load Foundation");
    ID pool = m0(m0(getclass("NSAutoreleasePool"),"alloc"),"init");
    ID version = m1(getclass("NSDictionary"),"dictionaryWithContentsOfFile:",
                    string("/System/Library/CoreServices/SystemVersion.plist"));
    const char *build = utf8(field(version,"ProductBuildVersion"));
    if (!build || strcmp(build,"7E18")) fail("unsupported firmware; expected 7E18");
    regular_path(argv[1],0);
    struct stat metadata_stat;
    if (stat(argv[1],&metadata_stat) || metadata_stat.st_size > 65536) fail("metadata exceeds 64 KiB");
    ID input = m1(getclass("NSDictionary"),"dictionaryWithContentsOfFile:",string(argv[1]));
    if (!is_class(input,"NSDictionary")) fail("metadata must be a dictionary plist");
    ID filename_value = field(input,"filename");
    if (!is_class(filename_value,"NSString")) fail("filename must be a string");
    const char *filename = utf8(filename_value);
    if (!component(filename)) fail("invalid filename");
    ID kind_value = field(input,"kind");
    if (kind_value && !is_class(kind_value,"NSString")) fail("kind must be a string");
    const char *kind = kind_value ? utf8(kind_value) : "song";
    if (!kind || (strcmp(kind,"song") && strcmp(kind,"feature-movie")))
        fail("kind must be song or feature-movie");
    int movie = !strcmp(kind,"feature-movie");
    const char *extension = strrchr(filename,'.');
    if (!extension || (movie
        ? (strcmp(extension,".m4v") && strcmp(extension,".mp4") && strcmp(extension,".mov"))
        : (strcmp(extension,".m4a") && strcmp(extension,".mp3") && strcmp(extension,".wav"))))
        fail("expected m4a/mp3/wav for song or m4v/mp4/mov for feature-movie");
    char folder[160], path[512];
    snprintf(folder,sizeof(folder),"LightTouch/%s",argv[2]);
    regular_path(MEDIA "LightTouch",1);
    snprintf(path,sizeof(path),MEDIA "%s",folder);
    regular_path(path,1);
    snprintf(path,sizeof(path),MEDIA "%s/%s",folder,filename);
    regular_path(path,0);
    if (access(path,R_OK)) fail("staged media is not readable by mobile");

    ID props = m0(getclass("NSMutableDictionary"),"dictionary");
    const char *source[] = {"title","artist","album","genre","album_artist","composer"};
    const char *target[] = {"itemName","artistName","playlistName","genre","playlistArtistName","composerName"};
    for (unsigned i=0; i<sizeof(source)/sizeof(source[0]); ++i) {
        ID value = field(input,source[i]);
        if (!value && i) continue;
        if (!is_class(value,"NSString")) fail("title/artist/album/genre must be strings");
        const char *text = utf8(value);
        if (!text || strlen(text)>4096 || (!i && !*text)) fail("invalid or oversized media metadata");
        set(props,target[i],value);
    }
    ID duration = field(input,"duration_ms");
    if (!is_class(duration,"NSNumber")) fail("duration_ms must be numeric");
    double ms = CALL(double,(ID,ID))(duration,selector("doubleValue"));
    if (!isfinite(ms) || ms <= 0 || ms > 86400000) fail("duration must be within one day");
    set(props,"duration",duration);
    const char *number_source[] = {"track_number","track_count","disc_number","disc_count"};
    const char *number_target[] = {"trackNumber","trackCount","discNumber","discCount"};
    for (unsigned i=0; i<4; ++i) {
        ID value = field(input,number_source[i]);
        if (!value) continue;
        if (!is_class(value,"NSNumber")) fail("track/disc metadata must be numeric");
        double n = CALL(double,(ID,ID))(value,selector("doubleValue"));
        if (!isfinite(n) || n < 1 || n > 65535 || n != floor(n)) fail("invalid track/disc number");
        set(props,number_target[i],value);
    }
    /* 7E18 ITMediaKindFromOTAMediaKindString maps feature-movie to kind 2
     * and sets has_video. Let MusicLibrary populate every related field. */
    set(props,"kind",string(kind));
    ID download = m0(getclass("NSMutableDictionary"),"dictionary");
    set(download,"mediaAssetFilename",filename_value);
    ID artwork = field(input,"artwork_filename");
    if (artwork) {
        if (!is_class(artwork,"NSString") || strcmp(utf8(artwork),"artwork.jpg")) fail("expected artwork.jpg");
        snprintf(path,sizeof(path),MEDIA "%s/artwork.jpg",folder);
        regular_path(path,0);
        struct stat st;
        if (stat(path,&st) || st.st_size > 2*1024*1024 || access(path,R_OK)) fail("invalid artwork file");
        set(download,"artworkAssetFilename",artwork);
    }
    set(props,"com.apple.iTunesStore.downloadInfo",download);

    int lock = open(MEDIA "LightTouch/.import.lock",O_RDWR|O_CREAT|O_NOFOLLOW,0600);
    if (lock < 0 || flock(lock,LOCK_EX|LOCK_NB)) fail("another media import is running");
    if (!dlopen("/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary",RTLD_NOW))
        fail("cannot load MusicLibrary");
    void *sqlite = dlopen("/usr/lib/libsqlite3.dylib",RTLD_NOW);
    if (!sqlite) fail("cannot load SQLite for import reconciliation");
    sql_open = dlsym(sqlite,"sqlite3_open_v2");
    sql_timeout = dlsym(sqlite,"sqlite3_busy_timeout");
    sql_exec = dlsym(sqlite,"sqlite3_exec");
    sql_prepare = dlsym(sqlite,"sqlite3_prepare_v2");
    sql_bind = dlsym(sqlite,"sqlite3_bind_text");
    sql_step = dlsym(sqlite,"sqlite3_step");
    sql_column = dlsym(sqlite,"sqlite3_column_int64");
    sql_finalize = dlsym(sqlite,"sqlite3_finalize");
    sql_close = dlsym(sqlite,"sqlite3_close");
    sql_error = dlsym(sqlite,"sqlite3_errmsg");
    if (!sql_open || !sql_timeout || !sql_exec || !sql_prepare || !sql_bind ||
        !sql_step || !sql_column || !sql_finalize || !sql_close || !sql_error) fail("SQLite API unavailable");
    ID library = m0(getclass("MusicLibrary"),"sharedMusicLibrary");
    const char *insert = "insertItemFromPurchaseFolder:withItemProperties:";
    if (!library || !CALL(int,(ID,ID,ID))(library,selector("respondsToSelector:"),selector(insert)))
        fail("MusicLibrary import service is unavailable");
    unsigned artwork_id = 0;
    int was_present = existing(folder,filename,&artwork_id);
    if (artwork && !was_present) {
        artwork_id = next_artwork_id();
        set(props,"itemId",CALL(ID,(ID,ID,unsigned))(getclass("NSNumber"),selector("numberWithUnsignedInt:"),artwork_id));
    }
    if (!was_present) {
        ID result = CALL(ID,(ID,ID,ID,ID))(library,selector(insert),string(folder),props);
        if (!result) fail("MusicLibrary declined import; retain staged media for reconciliation");
        m0(getclass("MusicLibrary"),"commitAllDeferredWork");
        m0(getclass("MusicLibrary"),"flush");
        if (!existing(folder,filename,&artwork_id)) fail("import not visible; retain staged media for reconciliation");
    }
    if (artwork) {
        if (!artwork_id) fail("existing track has no artwork ID; remove it in Music before importing again");
        import_artwork(folder,artwork_id);
    }
    /* Finish native post-sync sorting/index work before Music is launched.
     * Otherwise its SyncHelper starts that work itself and schedules a normal
     * terminateWithSuccess when the sync phase ends (7E18: 0x57bc4). */
    void *sync = dlopen("/System/Library/PrivateFrameworks/ITSync.framework/ITSync",RTLD_NOW);
    int (*postprocess)(ID,int) = sync ? dlsym(sync,"ITDBPrepServerPostProcessRun") : NULL;
    if (!postprocess || !postprocess(NULL,1))
        fail("music post-processing did not finish; retain staging for reconciliation");
    puts(was_present ? "already-imported" : "imported");
    fflush(stdout);
    m0(pool,"drain");
    close(lock);
    _exit(0);
}
