/* Import staged music or video through the guest's MusicLibrary purchase-folder service. The service owns
 * the item. SQLite below is read-only, for retry reconciliation; the item's year, which
 * the purchase-folder insert has no property for, goes through MusicLibrary's own connection.
 * There is no CRT in these ARMv6 executables; see armv6-toolchain/README.md.
 * -DITMEDIA_HOST_CHECK builds the metadata mapping alone for the Mac, so offline checks
 * run this file's mapping rather than a copy of it. */
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <math.h>
#include <dlfcn.h>
#include <sqlite3.h>

#define MEDIA "/var/mobile/Media/"
#define LIBRARY MEDIA "iTunes_Control/iTunes/iTunes Library.itlp/"
typedef void *ID;
static ID (*getclass)(const char *), (*selector)(const char *);
static void *send;
#define CALL(ret,args) ((ret (*)args)send)
static ID m0(ID o, const char *s) { return CALL(ID,(ID,ID))(o,selector(s)); }
static ID m1(ID o, const char *s, ID a) { return CALL(ID,(ID,ID,ID))(o,selector(s),a); }
static ID number(unsigned value) {
    return CALL(ID,(ID,ID,unsigned))(getclass("NSNumber"),selector("numberWithUnsignedInt:"),value);
}
static ID string(const char *s) {
    return CALL(ID,(ID,ID,const char *))(getclass("NSString"),selector("stringWithUTF8String:"),s);
}
static const char *utf8(ID o) { return CALL(const char *,(ID,ID))(o,selector("UTF8String")); }
static int is_class(ID o, const char *name) {
    return o && CALL(int,(ID,ID,ID))(o,selector("isKindOfClass:"),getclass(name));
}
static ID field(ID o, const char *key) { return m1(o,"objectForKey:",string(key)); }
static void set(ID o, const char *key, ID value) {
    CALL(void,(ID,ID,ID,ID))(o,selector("setObject:forKey:"),value,string(key));
}
static void fail(const char *reason) {
    fprintf(stderr,"itmedia: %s\n",reason);
    _exit(1);
}

/* Components are generated by the host. Never let metadata select a path
 * outside the dedicated staging tree, including through symlinks. */
static int component(const char *s) {
    size_t n = s ? strlen(s) : 0;
    if (!n || n > 128 || s[0] == '.') return 0;
    for (; *s; ++s) {
        if (!((*s >= 'a' && *s <= 'z') || (*s >= 'A' && *s <= 'Z') ||
              (*s >= '0' && *s <= '9') || *s == '-' || *s == '_' || *s == '.')) return 0;
    }
    return 1;
}
static void regular_path(const char *path, int directory) {
    struct stat st;
    if (lstat(path,&st) || (directory ? !S_ISDIR(st.st_mode) : !S_ISREG(st.st_mode)))
        fail("staged media path is missing or is not a regular file/directory");
    if (!directory && (st.st_size <= 0 || st.st_size > 1024LL*1024*1024))
        fail("staged file size is outside 1 byte..1 GiB");
}

/* Validate the host's metadata and build MusicLibrary's purchase-folder item properties
 * (7E18 -[MLMusicLibrary_SQL insertItemFromPurchaseFolder:withItemProperties:] keys).
 * Sets *artwork to the staged cover's file name and *year when present. */
static ID item_properties(ID input, const char **filename_out,
                          const char **artwork, unsigned *year) {
    ID filename_value = field(input,"filename");
    if (!is_class(filename_value,"NSString")) fail("filename must be a string");
    const char *filename = utf8(filename_value);
    if (!component(filename)) fail("invalid filename");
    ID kind_value = field(input,"kind");
    if (kind_value && !is_class(kind_value,"NSString")) fail("kind must be a string");
    const char *kind = kind_value ? utf8(kind_value) : "song";
    if (!kind || (strcmp(kind,"song") && strcmp(kind,"feature-movie")))
        fail("kind must be song or feature-movie");
    int movie = !strcmp(kind,"feature-movie");
    const char *extension = strrchr(filename,'.');
    if (!extension || (movie
        ? (strcmp(extension,".m4v") && strcmp(extension,".mp4") && strcmp(extension,".mov"))
        : (strcmp(extension,".m4a") && strcmp(extension,".mp3") && strcmp(extension,".wav"))))
        fail("expected m4a/mp3/wav for song or m4v/mp4/mov for feature-movie");

    ID props = m0(getclass("NSMutableDictionary"),"dictionary");
    const char *source[] = {"title","artist","album","album_artist","composer","genre"};
    const char *target[] = {"itemName","artistName","playlistName","playlistArtistName","composerName","genre"};
    for (unsigned i=0; i<sizeof(source)/sizeof(*source); ++i) {
        ID value = field(input,source[i]);
        if (!value && i) continue;
        if (!is_class(value,"NSString")) fail("text metadata must be strings");
        const char *text = utf8(value);
        if (!text || strlen(text)>4096 || (!i && !*text)) fail("invalid or oversized media metadata");
        set(props,target[i],value);
    }
    /* UInt16 in MusicLibrary's purchase dictionary reader. */
    const char *counts[] = {"track_number","track_count","disc_number","disc_count"};
    const char *count_target[] = {"trackNumber","trackCount","discNumber","discCount"};
    for (unsigned i=0; i<4; ++i) {
        ID value = field(input,counts[i]);
        if (!value) continue;
        double n = is_class(value,"NSNumber") ? CALL(double,(ID,ID))(value,selector("doubleValue")) : 0;
        if (!isfinite(n) || n != floor(n) || n < 1 || n > 65535) fail("track and disc numbers must be 1..65535");
        set(props,count_target[i],number((unsigned)n));
    }
    ID compilation = field(input,"compilation");
    if (compilation) {
        if (!is_class(compilation,"NSNumber")) fail("compilation must be a boolean");
        set(props,"compilation",
            CALL(ID,(ID,ID,int))(getclass("NSNumber"),selector("numberWithBool:"),
                                 CALL(signed char,(ID,ID))(compilation,selector("boolValue")) != 0));
    }
    *year = 0;
    ID year_value = field(input,"year");
    if (year_value) {
        double y = is_class(year_value,"NSNumber") ? CALL(double,(ID,ID))(year_value,selector("doubleValue")) : 0;
        if (!isfinite(y) || y != floor(y) || y < 1 || y > 9999) fail("year must be 1..9999");
        *year = (unsigned)y;
    }
    ID duration = field(input,"duration_ms");
    if (!is_class(duration,"NSNumber")) fail("duration_ms must be numeric");
    double ms = CALL(double,(ID,ID))(duration,selector("doubleValue"));
    if (!isfinite(ms) || ms <= 0 || ms > 86400000) fail("duration must be within one day");
    /* 7E18 purchase metadata accepts whole milliseconds. A fractional NSNumber
     * silently becomes total_time_ms=0 even when the file decodes correctly. */
    set(props,"duration",number((unsigned)fmax(1.0, floor(ms + 0.5))));
    /* 7E18 ITMediaKindFromOTAMediaKindString maps feature-movie to kind 2
     * and sets has_video. Let MusicLibrary populate every related field. */
    set(props,"kind",string(kind));
    *artwork = NULL;
    ID artwork_value = field(input,"artwork");
    if (artwork_value) {
        if (!is_class(artwork_value,"NSString") || strcmp(utf8(artwork_value),"artwork.jpg"))
            fail("expected artwork.jpg");
        *artwork = utf8(artwork_value);
    }
    ID download = m0(getclass("NSMutableDictionary"),"dictionary");
    set(download,"mediaAssetFilename",filename_value);
    set(props,"com.apple.iTunesStore.downloadInfo",download);
    *filename_out = filename;
    return props;
}

static void load_foundation(void) {
    void *objc = dlopen("/usr/lib/libobjc.A.dylib",RTLD_NOW);
    if (!objc) fail("cannot load Objective-C runtime");
    getclass = dlsym(objc,"objc_getClass");
    selector = dlsym(objc,"sel_registerName");
    send = dlsym(objc,"objc_msgSend");
    if (!getclass || !selector || !send ||
        !dlopen("/System/Library/Frameworks/Foundation.framework/Foundation",RTLD_NOW))
        fail("cannot load Foundation");
}

static ID read_metadata(const char *path) {
    regular_path(path,0);
    struct stat metadata_stat;
    if (stat(path,&metadata_stat) || metadata_stat.st_size > 65536) fail("metadata exceeds 64 KiB");
    ID input = m1(getclass("NSDictionary"),"dictionaryWithContentsOfFile:",string(path));
    if (!is_class(input,"NSDictionary")) fail("metadata must be a dictionary plist");
    return input;
}

#ifdef ITMEDIA_HOST_CHECK
/* Host check of the production metadata mapping. Artwork IDs are allocated
 * from the native library under the import lock, verified by booted QA. */
int main(int argc, char **argv) {
    if (argc != 4 || !component(argv[2])) fail("usage: itmedia-host metadata.plist staging-id out.plist");
    load_foundation();
    const char *filename, *artwork;
    unsigned year;
    ID props = item_properties(read_metadata(argv[1]),&filename,&artwork,&year);
    ID out = m0(getclass("NSMutableDictionary"),"dictionary");
    set(out,"properties",props);
    if (artwork) {
        set(out,"artwork",string(artwork));
    }
    if (year) set(out,"year",number(year));
    return CALL(signed char,(ID,ID,ID,signed char))(out,selector("writeToFile:atomically:"),string(argv[3]),1) ? 0 : 1;
}
#else
static __typeof__(sqlite3_open_v2) *sql_open;
static __typeof__(sqlite3_busy_timeout) *sql_timeout;
static __typeof__(sqlite3_exec) *sql_exec;
static __typeof__(sqlite3_prepare_v2) *sql_prepare;
static __typeof__(sqlite3_bind_text) *sql_bind;
static __typeof__(sqlite3_column_int64) *sql_column;
static __typeof__(sqlite3_step) *sql_step;
static __typeof__(sqlite3_finalize) *sql_finalize;
static __typeof__(sqlite3_close) *sql_close;
static __typeof__(sqlite3_errmsg) *sql_error;
static void database_failure(sqlite3 *db, const char *reason) {
    fprintf(stderr,"itmedia: %s: %s\n",reason,db ? sql_error(db) : "no connection");
    _exit(1);
}

/* 5.x replaced the iTunes Library.itlp databases with ML3's one MediaLibrary.sqlitedb. */
#define ML3_LIBRARY MEDIA "iTunes_Control/iTunes/MediaLibrary.sqlitedb"
static int ml3;

/* An old SQLite connection can retain the attached Locations schema while
 * Apple's sync service replaces its indexes. Reopen and reprepare only on
 * SQLITE_SCHEMA; every other error remains fatal, so uncertainty never replays
 * an import. These queries never mutate either database. */
static int read_query(const char *sql, const char *folder, const char *filename,
                      sqlite3_int64 *value, sqlite3_int64 *second) {
    for (unsigned attempt = 0; attempt < 3; ++attempt) {
        sqlite3 *db = NULL;
        sqlite3_stmt *stmt = NULL;
        int rc = sql_open(ml3 ? ML3_LIBRARY : LIBRARY "Library.itdb",&db,SQLITE_OPEN_READONLY,NULL);
        if (rc == SQLITE_OK) {
            sql_timeout(db,5000);
            if (folder && !ml3) rc = sql_exec(db,"ATTACH DATABASE '" LIBRARY "Locations.itdb' AS loc",NULL,NULL,NULL);
            if (rc == SQLITE_OK) rc = sql_prepare(db,sql,-1,&stmt,NULL);
            if (rc == SQLITE_OK && folder) rc = sql_bind(stmt,1,folder,-1,SQLITE_TRANSIENT);
            if (rc == SQLITE_OK && filename) rc = sql_bind(stmt,2,filename,-1,SQLITE_TRANSIENT);
            if (rc == SQLITE_OK) rc = sql_step(stmt);
        }
        if (rc != SQLITE_ROW && rc != SQLITE_DONE &&
            (rc != SQLITE_SCHEMA || attempt == 2))
            database_failure(db,"music library query failed");
        if (rc == SQLITE_ROW) {
            *value = sql_column(stmt,0);
            if (second) *second = sql_column(stmt,1);
        }
        sql_finalize(stmt);
        sql_close(db);
        if (rc != SQLITE_SCHEMA) return rc;
        usleep(50000);
    }
    fail("music library schema did not settle");
    return SQLITE_ERROR;
}

/* Read identity and the native artwork ID at the immutable staged location.
 * Errors are fatal: an uncertain prior import must never replay. */
static sqlite3_int64 existing(const char *folder, const char *filename, unsigned *artwork_id) {
    const char *sql = ml3
        ? "SELECT item.item_pid,e.artwork_cache_id FROM item JOIN item_extra e ON e.item_pid=item.item_pid "
          "JOIN base_location b ON b.base_location_id=item.base_location_id WHERE b.path=? AND e.location=? LIMIT 1"
        : "SELECT item.pid,item.artwork_cache_id FROM item NOT INDEXED JOIN loc.location l ON l.item_pid=item.pid "
          "JOIN loc.base_location b ON b.id=l.base_location_id "
          "WHERE b.path=? AND l.location=? LIMIT 1";
    sqlite3_int64 pid = 0, art = 0;
    if (read_query(sql,folder,filename,&pid,&art) != SQLITE_ROW) return 0;
    *artwork_id = (unsigned)art;
    return pid;
}

/* ArtworkCache uses the purchase itemId as its string key. Choose an unused
 * ID from the native library under the import lock; only Apple writes either DB. */
static unsigned next_artwork_id(void) {
    sqlite3_int64 last = 0;
    if (read_query("SELECT COALESCE(MAX(artwork_cache_id),0) FROM item NOT INDEXED",NULL,NULL,&last,NULL) != SQLITE_ROW)
        fail("cannot allocate artwork ID");
    if (last < 0 || last >= 0xffffffffLL) fail("artwork ID space exhausted");
    return (unsigned)(last+1);
}
static void import_artwork(const char *folder, unsigned identifier) {
    char path[512], key[32];
    snprintf(path,sizeof(path),MEDIA "%s/artwork.jpg",folder);
    ID data = m1(getclass("NSData"),"dataWithContentsOfFile:",string(path));
    void *cache = dlopen("/System/Library/PrivateFrameworks/ArtworkCache.framework/ArtworkCache",RTLD_NOW);
    int (*process)(ID,ID,ID,ID) = cache ? dlsym(cache,"ArtworkCache_ProcessArtworkData") : NULL;
    ID *albums = cache ? dlsym(cache,"kArtworkCacheCategory_Albums") : NULL;
    if (!process || !albums || !*albums || !data) fail("artwork service unavailable");
    if (mkdir(MEDIA "Purchases",0755) && errno != EEXIST) fail("cannot create purchase artwork folder");
    regular_path(MEDIA "Purchases",1);
    if (mkdir(MEDIA "Purchases/MobileArtworkDB",0755) && errno != EEXIST) fail("cannot create artwork cache folder");
    regular_path(MEDIA "Purchases/MobileArtworkDB",1);
    ID url = m1(getclass("NSURL"),"fileURLWithPath:",string(MEDIA "Purchases/MobileArtworkDB"));
    snprintf(key,sizeof(key),"%u",identifier);
    if (!process(url,string(key),*albums,data)) fail("artwork processing failed; retain staging for reconciliation");
}

/* Through MusicLibrary's own writer connection: it opens the library with its own
 * SQLite VFS, so a second plain connection is read-only. No 7E18 trigger or index
 * covers item.year, and the purchase-folder insert has no property for it. */
static void record_year(sqlite3_int64 pid, unsigned year) {
    void *support = dlopen("/System/Library/PrivateFrameworks/AppSupport.framework/AppSupport",RTLD_NOW);
    void *library = dlopen("/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary",RTLD_NOW);
    void *(*shared_store)(void) = library ? dlsym(library,"MLSDBGetSharedRecordStore") : NULL;
    void *(*store_database)(void *) = support ? dlsym(support,"CPRecordStoreGetDatabase") : NULL;
    void *(*for_writing)(void *) = support ? dlsym(support,"CPSqliteDatabaseConnectionForWriting") : NULL;
    int (*perform)(void *,ID) = support ? dlsym(support,"CPSqliteConnectionPerformSQL") : NULL;
    if (!shared_store || !store_database || !for_writing || !perform) fail("MusicLibrary database API unavailable");
    void *connection = for_writing(store_database(shared_store()));
    char sql[96];
    snprintf(sql,sizeof(sql),"UPDATE item SET year=%u WHERE pid=%lld",year,(long long)pid);
    int rc = connection ? perform(connection,string(sql)) : SQLITE_ERROR;
    if (rc != SQLITE_DONE && rc != SQLITE_OK) fail("year not recorded; retain staged media for reconciliation");
}

/* 5.x: ML3's own importer (what the store's downloads use), given an MLTrackImport: the
 * entity properties under MusicLibrary's exported ML3TrackProperty names, the asset path and
 * the cover's bytes, which it renders into its artwork cache itself. It runs the insert in one
 * transaction and calls its completion block (BOOL success, int64 pid) before returning. */
struct block_descriptor { unsigned long reserved, size; };
struct block { void *isa; int flags, reserved; void *invoke; const struct block_descriptor *descriptor; };
static struct { int done, ok; sqlite3_int64 pid; } ml3_result;
static void ml3_finished(struct block *b, signed char ok, long long pid) {
    (void)b; ml3_result.done = 1; ml3_result.ok = ok; ml3_result.pid = pid;
}
static sqlite3_int64 ml3_import(void *music, ID input, const char *folder, const char *filename, const char *artwork) {
    static const struct block_descriptor descriptor = {0, sizeof(struct block)};
    void **global = dlsym(RTLD_DEFAULT,"_NSConcreteGlobalBlock");
    ID track = m0(m0(getclass("MLTrackImport"),"alloc"),"init");
    /* sharedLibrary is read-only outside the system's writers; this process opens its own writer. */
    ID writer = CALL(ID,(ID,ID,ID,signed char))(m0(getclass("ML3MusicLibrary"),"alloc"),selector("initWithPath:enableWrites:"),
                                                string(ML3_LIBRARY),1);
    ID importer = writer ? m1(m0(getclass("ML3TrackImporter"),"alloc"),"initWithMusicLibrary:",writer) : NULL;
    if (!global || !track || !importer) fail("ML3 importer unavailable");
    const char *source[] = {"title","artist","album","album_artist","composer","genre","track_number","track_count",
                            "disc_number","disc_count","year","compilation"};
    const char *target[] = {"ML3TrackPropertyTitle","ML3TrackPropertyArtist","ML3TrackPropertyAlbum",
                            "ML3TrackPropertyAlbumArtist","ML3TrackPropertyComposer","ML3TrackPropertyGenre",
                            "ML3TrackPropertyTrackNumber","ML3TrackPropertyTrackCount","ML3TrackPropertyDiscNumber",
                            "ML3TrackPropertyDiscCount","ML3TrackPropertyYear","ML3TrackPropertyIsCompilation"};
    for (unsigned i=0; i<sizeof(source)/sizeof(*source); ++i) {
        ID value = field(input,source[i]);
        ID *key = dlsym(music,target[i]);
        if (!key || !*key) fail("ML3 track property unavailable");
        if (value) CALL(void,(ID,ID,ID,ID))(track,selector("setValue:forEntityProperty:"),value,*key);
    }
    ID *total = dlsym(music,"ML3TrackPropertyTotalTime");
    if (!total || !*total) fail("ML3 track property unavailable");
    double ms = CALL(double,(ID,ID))(field(input,"duration_ms"),selector("doubleValue"));
    CALL(void,(ID,ID,ID,ID))(track,selector("setValue:forEntityProperty:"),number((unsigned)fmax(1.0,floor(ms+0.5))),*total);
    /* ML3's media types are not MPMediaType's: 9B206 MusicLibrary's MLMediaType description names bit 8 "Song",
     * and Music's song queries select item.media_type & 8. With 1 the row is counted (Music shows its tabs) but
     * never listed. */
    CALL(void,(ID,ID,unsigned))(track,selector("setMediaType:"),8);
    char path[512];
    snprintf(path,sizeof(path),MEDIA "%s/%s",folder,filename);
    m1(track,"setAssetFilePath:",string(path));
    if (artwork) {
        snprintf(path,sizeof(path),MEDIA "%s/artwork.jpg",folder);
        ID data = m1(getclass("NSData"),"dataWithContentsOfFile:",string(path));
        if (!data) fail("cannot read artwork");
        m1(track,"setArtworkData:",data);
    }
    struct block done = {*global, 1<<28, 0, (void *)ml3_finished, &descriptor};
    CALL(void,(ID,ID,ID,void *))(importer,selector("importTrack:withCompletionBlock:"),track,&done);
    if (!ml3_result.done || !ml3_result.ok || !ml3_result.pid)
        fail("MusicLibrary declined import; retain staged media for reconciliation");
    return ml3_result.pid;
}

/* 5.x: Music plays only tracks whose item_extra.integrity verifies (ML3TrackIntegrityVerify). The importer
 * computes it through FairPlay (FairPlayCandyBarCompute), which serves only processes carrying a fairplay-client
 * entitlement (itmedia.entitlements); without one it logs -42180 and leaves the column NULL, and Music lists the
 * song but will not play it. */
static int ml3_has_integrity(sqlite3_int64 pid) {
    char sql[128];
    sqlite3_int64 has = 0;
    snprintf(sql,sizeof(sql),"SELECT integrity IS NOT NULL FROM item_extra WHERE item_pid=%lld",(long long)pid);
    return read_query(sql,NULL,NULL,&has,NULL) == SQLITE_ROW && has;
}

__attribute__((naked)) void _start(void) {
    __asm__ volatile("ldr r0, [sp]\n\tadd r1, sp, #4\n\tb _main");
}
int main(int argc, char **argv) {
    if (argc != 3 || !component(argv[2]))
        fail("usage: itmedia metadata.plist staging-id");
    if (getuid() == 0 && (setgid(501) || setuid(501))) fail("cannot become mobile");
    if (getuid() != 501) fail("must run as mobile or root");
    setenv("HOME","/var/mobile",1);
    load_foundation();
    ID pool = m0(m0(getclass("NSAutoreleasePool"),"alloc"),"init");
    const char *filename, *artwork;
    unsigned year;
    ID input = read_metadata(argv[1]);
    ID props = item_properties(input,&filename,&artwork,&year);
    char folder[160], path[512];
    snprintf(folder,sizeof(folder),"LightTouch/%s",argv[2]);
    regular_path(MEDIA "LightTouch",1);
    snprintf(path,sizeof(path),MEDIA "%s",folder);
    regular_path(path,1);
    snprintf(path,sizeof(path),MEDIA "%s/%s",folder,filename);
    regular_path(path,0);
    if (access(path,R_OK)) fail("staged media is not readable by mobile");
    if (artwork) {
        snprintf(path,sizeof(path),MEDIA "%s/artwork.jpg",folder);
        regular_path(path,0);
        struct stat st;
        if (stat(path,&st) || st.st_size > 2*1024*1024 || access(path,R_OK)) fail("invalid artwork file");
    }

    int lock = open(MEDIA "LightTouch/.import.lock",O_RDWR|O_CREAT|O_NOFOLLOW,0600);
    if (lock < 0 || flock(lock,LOCK_EX|LOCK_NB)) fail("another media import is running");
    void *music = dlopen("/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary",RTLD_NOW);
    if (!music) fail("cannot load MusicLibrary");
    void *sqlite = dlopen("/usr/lib/libsqlite3.dylib",RTLD_NOW);
    if (!sqlite) fail("cannot load SQLite for import reconciliation");
    sql_open = dlsym(sqlite,"sqlite3_open_v2");
    sql_timeout = dlsym(sqlite,"sqlite3_busy_timeout");
    sql_exec = dlsym(sqlite,"sqlite3_exec");
    sql_prepare = dlsym(sqlite,"sqlite3_prepare_v2");
    sql_bind = dlsym(sqlite,"sqlite3_bind_text");
    sql_column = dlsym(sqlite,"sqlite3_column_int64");
    sql_step = dlsym(sqlite,"sqlite3_step");
    sql_finalize = dlsym(sqlite,"sqlite3_finalize");
    sql_close = dlsym(sqlite,"sqlite3_close");
    sql_error = dlsym(sqlite,"sqlite3_errmsg");
    if (!sql_open || !sql_timeout || !sql_exec || !sql_prepare || !sql_bind ||
        !sql_column ||
        !sql_step || !sql_finalize || !sql_close || !sql_error) fail("SQLite API unavailable");
    ID library = m0(getclass("MusicLibrary"),"sharedMusicLibrary");
    const char *insert = "insertItemFromPurchaseFolder:withItemProperties:";
    /* The capability, not a build list: 3.1 through 4.x answer this insert over the
     * iTunes Library.itlp SQLite library the queries below read; 5.x has ML3's importer instead. */
    if (!library || !CALL(int,(ID,ID,ID))(library,selector("respondsToSelector:"),selector(insert))) {
        ml3 = getclass("ML3TrackImporter") && getclass("MLTrackImport") && getclass("ML3MusicLibrary");
        if (!ml3) fail("unsupported firmware: no MusicLibrary import service");
        if (field(input,"kind") && strcmp(utf8(field(input,"kind")),"song")) fail("unsupported firmware: movies need 4.x or earlier");
        m0(getclass("ML3MusicLibrary"),"sharedLibrary");   /* creates the library on a device that has none */
        unsigned artwork_id = 0;
        sqlite3_int64 pid = existing(folder,filename,&artwork_id);
        int was_present = pid != 0;
        if (!was_present && !(pid = ml3_import(music,input,folder,filename,artwork)))
            fail("import not visible; retain staged media for reconciliation");
        if (!was_present && !existing(folder,filename,&artwork_id))
            fail("import not visible; retain staged media for reconciliation");
        if (!ml3_has_integrity(pid))
            fail("MusicLibrary stored the track without its integrity; Music would list it but not play it");
        puts(was_present ? "already-imported" : "imported");
        fflush(stdout);
        m0(pool,"drain");
        close(lock);
        _exit(0);
    }
    unsigned artwork_id = 0;
    sqlite3_int64 pid = existing(folder,filename,&artwork_id);
    int was_present = pid != 0;
    if (artwork && !was_present) {
        artwork_id = next_artwork_id();
        set(props,"itemId",number(artwork_id));
    }
    if (artwork) {
        if (!artwork_id) fail("existing track has no artwork ID; remove it in Music before importing again");
        import_artwork(folder,artwork_id);
    }
    if (!was_present) {
        ID result = CALL(ID,(ID,ID,ID,ID))(library,selector(insert),string(folder),props);
        if (!result) fail("MusicLibrary declined import; retain staged media for reconciliation");
        m0(getclass("MusicLibrary"),"commitAllDeferredWork");
        m0(getclass("MusicLibrary"),"flush");
        if (!(pid = existing(folder,filename,&artwork_id))) fail("import not visible; retain staged media for reconciliation");
    }
    if (year) record_year(pid,year);
    /* Finish native post-sync sorting/index work before Music is launched.
     * Otherwise its SyncHelper starts that work itself and schedules a normal
     * terminateWithSuccess when the sync phase ends (7E18: 0x57bc4). */
    void *sync = dlopen("/System/Library/PrivateFrameworks/ITSync.framework/ITSync",RTLD_NOW);
    int (*postprocess)(ID,int) = sync ? dlsym(sync,"ITDBPrepServerPostProcessRun") : NULL;
    if (!postprocess || !postprocess(NULL,1))
        fail("music post-processing did not finish; retain staging for reconciliation");
    sleep(2);
    if (!existing(folder,filename,&artwork_id)) fail("the music library dropped the import");
    puts(was_present ? "already-imported" : "imported");
    fflush(stdout);
    m0(pool,"drain");
    close(lock);
    _exit(0);
}
#endif
