#!/usr/bin/env python3
"""Generate gli_fwd.h for glishim.c from docs/ipad1/gli-dispatch-7B500.tsv.

One entry per 3.2.2 dispatch slot (826). A slot OpenGLES exports a trampoline
for, or that the real GLEngine fills for ES1 or ES2, gets a forwarder that
sends its arguments to the host under the 3.1.3 WIRE slot number (the host
decoder keys on those; 3.2 inserted three slots at 761, so wire = slot - 3 from
764 up). Every other slot, and any slot with no 3.1.3 equivalent, gets a stub
that logs once and returns 0 -- the trampolines never null-check.

Argument counts come from the TSV's macOS prototype column for slots < 764 and
from the table below for the ES tail, which has no macOS prototype.

    gligen.py OUT.h     generate
    gligen.py --check   self-check only
"""
import os
import re
import sys

N_SLOTS = 826
TSV = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "../../docs/ipad1/gli-dispatch-7B500.tsv")

# gl.h / glext.h argument counts (GC excluded) for the ES tail, slots 764-825.
TAIL_ARGC = {
    "glAlphaFuncx": 2, "glClearColorx": 4, "glClearDepthf": 1, "glClearDepthx": 1,
    "glClipPlanef": 2, "glClipPlanex": 2, "glColor4x": 4, "glDepthRangef": 2,
    "glDepthRangex": 2, "glFogx": 2, "glFogxv": 2, "glFrustumf": 6, "glFrustumx": 6,
    "glGetClipPlanef": 2, "glGetClipPlanex": 2, "glGetFixedv": 2,
    "glGetLightxv": 3, "glGetMaterialxv": 3, "glGetTexEnvxv": 3,
    "glGetTexParameterxv": 3, "glLightModelx": 2, "glLightModelxv": 2,
    "glLightx": 3, "glLightxv": 3, "glLineWidthx": 1, "glLoadMatrixx": 1,
    "glMaterialx": 3, "glMaterialxv": 3, "glMultMatrixx": 1, "glNormal3x": 3,
    "glOrthof": 6, "glOrthox": 6, "glPointSizex": 1, "glPolygonOffsetx": 2,
    "glRotatex": 4, "glScalex": 3, "glTexEnvx": 3, "glTexEnvxv": 3,
    "glTexParameterx": 3, "glTexParameterxv": 3, "glTranslatex": 3,
    "glMultiTexCoord4x": 5, "glSampleCoveragex": 2, "glPointParameterx": 2,
    "glPointParameterxv": 2, "glPointSizePointerOES": 3,
    "glCurrentPaletteMatrixOES": 1, "glLoadPaletteFromModelViewMatrixOES": 0,
    "glMatrixIndexPointerOES": 4, "glWeightPointerOES": 4,
    "glDrawTexsOES": 5, "glDrawTexiOES": 5, "glDrawTexxOES": 5, "glDrawTexfOES": 5,
    "glDrawTexsvOES": 1, "glDrawTexivOES": 1, "glDrawTexxvOES": 1, "glDrawTexfvOES": 1,
    "glShaderBinary": 5, "glGetShaderPrecisionFormat": 4,
    "glReleaseShaderCompiler": 0, "glFramebufferParameteriAPPLE": 3,
}


def load():
    """-> list of (slot, name, wire or None, argc or None) for every slot."""
    rows = []
    for line in open(TSV):
        if line.startswith(("#", "slot\t")):
            continue
        f = line.rstrip("\n").split("\t")
        slot, name = int(f[0]), f[4]
        wanted = f[5] == "Y" or f[6] == "Y" or f[7] == "Y"
        wire = int(f[8]) if f[8].isdigit() else None
        proto = f[9] if len(f) > 9 else ""
        argc = None
        if slot >= 764:
            argc = TAIL_ARGC.get(name)
        elif proto and "double" not in proto and "clampd" not in proto:
            # "void (GLIContext, a, b)" -> 2
            argc = proto[proto.index("(") + 1:proto.rindex(")")].count(",")
        rows.append((slot, name, wire if wanted else None, argc))
    return rows


def check(rows):
    assert len(rows) == N_SLOTS and [r[0] for r in rows] == list(range(N_SLOTS))
    by = {r[1].rstrip("*"): r for r in rows}
    # Known ES1 wire numbers the host already decodes (gles.h).
    assert by["glOrthof"][2] == 791 and by["glOrthof"][3] == 6
    assert by["glAlphaFuncx"][2] == 761 and by["glClearDepthf"][2] == 763
    assert by["glTexImage2D"][2] == 301 and by["glTexImage2D"][3] == 9
    assert by["glDrawArrays"][3] == 3 and by["glClear"][3] == 1
    # ES2 core sits below 761 with identical numbering.
    assert by["glUseProgram"][2] == 600 and by["glUniformMatrix2fv"][3] == 4
    assert by["glVertexAttribPointer"][2] is not None
    # New in 3.2: no wire number, so never forwarded.
    assert by["glFramebufferParameteriAPPLE"][2] is None
    for slot, name, wire, argc in rows:
        if wire is not None:
            assert argc is not None, "no argc for forwarded %s (%d)" % (name, slot)
            assert wire == (slot if slot < 761 else slot - 3), (slot, name, wire)


rows = load()
check(rows)
if sys.argv[1:] == ["--check"]:
    print("gligen self-check OK: %d slots, %d forwarded"
          % (len(rows), sum(r[2] is not None for r in rows)))
    sys.exit(0)

out = ["/* Generated by gligen.py from gli-dispatch-7B500.tsv -- do not edit. */",
       "#define GLI_N_SLOTS %d" % N_SLOTS, ""]
for slot, name, wire, argc in rows:
    if wire is None:
        out.append("static int g%d(void *gc) { (void)gc; return gles_unimpl(%d); }"
                   % (slot, slot))
        continue
    params = "".join(", unsigned a%d" % i for i in range(argc))
    args = ", ".join("a%d" % i for i in range(argc)) or "0"
    out.append("static int g%d(void *gc%s) /* %s */ { return (int)qc(%d, gc, %d, A(%s)); }"
               % (slot, params, name, wire, argc, args))
out.append("")
# Slot numbers by name, so glishim.c's overrides cannot name the wrong slot.
for slot, name, wire, argc in rows:
    if wire is not None:
        out.append("#define GLI_SLOT_%s %d" % (name, slot))
out.append("")
out.append("static void *const gli_fwd_table[GLI_N_SLOTS] = {")
for i in range(0, N_SLOTS, 8):
    out.append("    %s," % ", ".join("(void *)g%d" % j for j in range(i, min(i + 8, N_SLOTS))))
out.append("};")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
print("wrote %s" % sys.argv[1])
