/* Actual MBX handlers and measured decoder under ASan/UBSan.
 *
 * Synthetic RAM is an expected-pixel oracle; it is not native startup proof.
 * No unsupported EVM acknowledgment is generated by these handlers.
 *
 * SLICE include/hw/arm/mbx_fill.h file
 * SLICE hw/arm/mbx_fill.c define RING_|HEADER|SUBMIT|PAGES
 * SLICE hw/arm/mbx_fill.c fn load_le32 reject mbx_fill_reset mbx_fill_write
 * SLICE hw/arm/ipod_touch_mbx.c define MBX_[A-Z0-9_]+[[:space:]]
 * SLICE include/hw/arm/ipod_touch_mbx.h typedef IPodTouchMBXState
 * SLICE:handlers hw/arm/ipod_touch_mbx.c fn ipod_touch_mbx1_read ipod_touch_mbx_update_irq ipod_touch_mbx1_write ipod_touch_mbx_reset
 */
#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
typedef uint64_t hwaddr;
typedef int SysBusDevice, MemoryRegion, DeviceState;
typedef int *qemu_irq;
typedef struct { bool pending; int64_t deadline; } QEMUTimer;
#define IPOD_TOUCH_MBX(s) ((IPodTouchMBXState *)(s))
#define QEMU_CLOCK_VIRTUAL 0
#define MBX_TRACE(...) ((void)0)
static int64_t qemu_clock_get_ns(int c) { return 0; }
static void qemu_set_irq(int *irq, int v) { if (irq) *irq = !!v; }
static void qemu_irq_lower(int *irq) { if (irq) *irq = 0; }
static void timer_mod(QEMUTimer *t, int64_t at) { t->pending = true; t->deadline = at; }
static void timer_del(QEMUTimer *t) { t->pending = false; }
#include "slice.h"

#define BASE 0x08000000u
#define SIZE 0x200000u
static uint8_t ram[SIZE];
static unsigned writes, fail_at;
static uint8_t *mbx_fill_guest_ram(void *o, uint32_t pa, uint32_t n) {
    return pa >= BASE && (uint64_t)pa + n <= BASE + SIZE ? ram + (pa - BASE) : NULL;
}
static void mbx_fill_guest_write(void *o, uint32_t pa, uint32_t v) {
    IPodTouchMBXState *s = o;
    uint8_t *p = mbx_fill_guest_ram(o, pa, 4);
    assert(p);
    if (fail_at && ++writes == fail_at) { s->fill_dma_failed = true; return; }
    if (!fail_at) writes++;
    for (unsigned i = 0; i < 4; i++) p[i] = v >> (8*i);
}
#include "handlers.h"

static IPodTouchMBXState s;
static int line;
#define WR(a,v) ipod_touch_mbx1_write(&s, (a), (v), 4)
#define RD(a) ipod_touch_mbx1_read(&s, (a), 4)
static const uint32_t packet[16] = {
    0xa0060500,0x823000,0x94060500,0,0x30000000,0x60800200,
    0x8000f0f0,0xff000000,0,0x014001e0,
    0x70000000,0x70000000,0x70000000,0x70000000,0x70000000,0x70000000
};
static void setup(void) {
    memset(&s, 0, sizeof s); memset(ram, 0x5a, sizeof ram);
    s.fill_enabled = true; s.irq = &line; line = 0;
    assert(RD(0x1020)==0); WR(0x1020,1); assert(RD(0x1020)==0x10001);
    fail_at = 0; writes = 0;
    memset(ram + 0x1000, 0, 4096);
    WR(0x1008, BASE + 0x1000);
    for (unsigned i = 0; i < 150; i++) {
        mbx_fill_guest_write(&s, BASE + 0x1000 + (0x23+i)*4, BASE + 0x40000 + i*8192);
    }
    writes = 0;
}
static void stage(unsigned count) {
    for (unsigned i = 0; i < count; i++) WR(0xa00000 + i*4, packet[i]);
}
static void submit(void) { WR(0xa00000, 0xf0000000); }
int main(void) {
    setup(); WR(0x130, 0x400); stage(16);
    assert(!writes && !line && !RD(0x12c));
    submit(); assert(writes == 153600 && line && RD(0x12c) == 0x400);
    assert(RD(0x12c) == 0x400 && line);
    for (unsigned i = 0; i < 150; i++) {
        uint8_t *p = ram + 0x40000 + i*8192;
        for (unsigned j = 0; j < 4096; j += 4) {
            assert(p[j] == 0 && p[j+1] == 0 && p[j+2] == 0 && p[j+3] == 0xff);
        }
        assert(p[4096] == 0x5a);
    }
    WR(0x130, 0); assert(!line && RD(0x12c) == 0x400);
    WR(0x130, 0x400); assert(line);
    WR(0x134, 0x400); assert(!line && !RD(0x12c));
    writes = 0; stage(15); submit(); assert(!writes && !line && !RD(0x12c)); /* stale tail */
    setup(); stage(16);
    mbx_fill_guest_write(&s, BASE+0x1000+(0x23+149)*4, 0); writes=0;
    WR(0x130,0x400); submit(); assert(!writes && !line && !RD(0x12c));
    setup(); stage(16); WR(0x130,0x400); fail_at=153600; submit();
    assert(s.fill_dma_failed && !line && !RD(0x12c)); /* partial DMA never completes */
    setup(); stage(16); WR(0x130,0x400);
    ipod_touch_mbx_reset((DeviceState *)&s); assert(!line && !RD(0x12c));
    writes=0; submit(); assert(!writes && !RD(0x12c));
    setup(); WR(0x130,0x140); WR(0x838,1); WR(0x6d8,0x09000000);
    WR(0x814,1); WR(0x818,1); WR(0x81c,1);
    assert(!writes && !line && !RD(0x12c)); /* no fake EVM/context events */
    setup(); for (unsigned i=0;i<16;i++) ipod_touch_mbx1_write(&s,0xa00000+i*4,packet[i],2);
    submit(); assert(!writes && !RD(0x12c)); /* partial-width ring not admitted */
    setup();WR(0x1020,0); assert(!RD(0x1020)); stage(16); WR(0x130,0x400); submit();
    assert(!writes && !line && !RD(0x12c)); /* No DMA through disabled GART. */
    assert(ram[0x40003]==0x5a);
    WR(0x1020,0x10000); assert(!RD(0x1020)); /* Guest cannot forge ready. */
    WR(0x1020,1); assert(RD(0x1020)==0x10001);
    stage(16); submit(); assert(writes==153600 && RD(0x12c)==0x400);
    ipod_touch_mbx_reset((DeviceState *)&s);assert(!RD(0x1020));
    puts("PASS: production handlers execute exact fill; IRQ/mask/W1C; fresh packet; late PTE refusal; DMA failure withholding completion; reset; unsupported startup/context and widths");
}
